version: '3'

services:
  db:
    container_name: db
    image: mysql:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - ./.env

  app:
    container_name: app
    build: ./nextcloud
    restart: always
    volumes:
      - app:/var/www/nextcloud
      - ./nextcloud/apps:/var/www/nextcloud/apps
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  db:
  app:
